// <auto-generated />
using System;
using ArchiX.Library.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchiX.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124150027_DilPaketi01")]
    partial class DilPaketi01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArchiX.Library.Entities.ConnectionAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NormalizedServer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawConnectionMasked")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Result");

                    b.HasIndex("StatusId");

                    b.ToTable("ConnectionAudits", (string)null);
                });

            modelBuilder.Entity("ArchiX.Library.Entities.ConnectionServerWhitelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidr")
                        .HasMaxLength(43)
                        .HasColumnType("nvarchar(43)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnvScope")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ServerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvScope");

                    b.HasIndex("StatusId");

                    b.HasIndex("Cidr", "IsActive");

                    b.HasIndex("ServerName", "IsActive");

                    b.ToTable("ConnectionServerWhitelists", null, t =>
                        {
                            t.HasCheckConstraint("CK_Whitelist_ServerOrCidr", "[ServerName] IS NOT NULL OR [Cidr] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.FilterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("ItemType", "Code")
                        .IsUnique();

                    b.ToTable("FilterItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Equals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "NotEquals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "StartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "NotStartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "EndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "NotEndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "Contains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "NotContains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "Between",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "NotBetween",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "GreaterThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 12,
                            Code = "GreaterThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "LessThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "LessThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 15,
                            Code = "In",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 16,
                            Code = "NotIn",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 17,
                            Code = "IsNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 18,
                            Code = "IsNotNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.LanguagePack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("ItemType", "EntityName", "FieldName", "Code", "Culture")
                        .IsUnique()
                        .HasFilter("[EntityName] IS NOT NULL AND [FieldName] IS NOT NULL");

                    b.ToTable("LanguagePacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Equals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilene eşit olmalı",
                            DisplayName = "Eşittir",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "Equals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be equal to the given one",
                            DisplayName = "Equals",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "NotEquals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilene eşit olmamalı",
                            DisplayName = "Eşit Değil",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "NotEquals",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not be equal to the given one",
                            DisplayName = "Not Equal",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "StartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyle başlamalı",
                            DisplayName = "Başlar",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "StartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must start with the given text",
                            DisplayName = "Starts With",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "NotStartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyle başlamamalı",
                            DisplayName = "Başlamaz",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "NotStartsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not start with the given text",
                            DisplayName = "Does Not Start With",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 9,
                            Code = "EndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyle bitmeli",
                            DisplayName = "Biter",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 10,
                            Code = "EndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must end with the given text",
                            DisplayName = "Ends With",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 11,
                            Code = "NotEndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyle bitmemeli",
                            DisplayName = "Bitmez",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 12,
                            Code = "NotEndsWith",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not end with the given text",
                            DisplayName = "Does Not End With",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "Contains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyi içermeli",
                            DisplayName = "İçerir",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 14,
                            Code = "Contains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must contain the given text",
                            DisplayName = "Contains",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 15,
                            Code = "NotContains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilen ifadeyi içermemeli",
                            DisplayName = "İçermez",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 16,
                            Code = "NotContains",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not contain the given text",
                            DisplayName = "Does Not Contain",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 17,
                            Code = "Between",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer alt ve üst sınırlar arasında (dahil) olmalı",
                            DisplayName = "Arasında",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 18,
                            Code = "Between",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be between lower and upper bounds (inclusive)",
                            DisplayName = "Between",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 19,
                            Code = "NotBetween",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer alt ve üst sınırlar arasında olmamalı",
                            DisplayName = "Arasında Değil",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 20,
                            Code = "NotBetween",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not be between the given bounds",
                            DisplayName = "Not Between",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 21,
                            Code = "GreaterThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilenden büyük olmalı",
                            DisplayName = "Büyüktür",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 22,
                            Code = "GreaterThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be greater than the given one",
                            DisplayName = "Greater Than",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 23,
                            Code = "GreaterThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilenden büyük veya eşit olmalı",
                            DisplayName = "Büyük veya Eşittir",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 24,
                            Code = "GreaterThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be greater than or equal to the given one",
                            DisplayName = "Greater Than Or Equal",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 25,
                            Code = "LessThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilenden küçük olmalı",
                            DisplayName = "Küçüktür",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 26,
                            Code = "LessThan",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be less than the given one",
                            DisplayName = "Less Than",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 27,
                            Code = "LessThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer belirtilenden küçük veya eşit olmalı",
                            DisplayName = "Küçük veya Eşittir",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 28,
                            Code = "LessThanOrEqual",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be less than or equal to the given one",
                            DisplayName = "Less Than Or Equal",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 29,
                            Code = "In",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer verilen listedeki öğelerden biri olmalı",
                            DisplayName = "İçinde",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 30,
                            Code = "In",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be one of the provided list items",
                            DisplayName = "In Set",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 31,
                            Code = "NotIn",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer verilen listedeki öğelerden biri olmamalı",
                            DisplayName = "İçinde Değil",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 32,
                            Code = "NotIn",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not be any of the provided list items",
                            DisplayName = "Not In Set",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 33,
                            Code = "IsNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer null olmalı",
                            DisplayName = "Boş (Null)",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 34,
                            Code = "IsNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must be null",
                            DisplayName = "Is Null",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 35,
                            Code = "IsNotNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Değer null olmamalı",
                            DisplayName = "Boş Değil",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 36,
                            Code = "IsNotNull",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Value must not be null",
                            DisplayName = "Is Not Null",
                            EntityName = "FilterItem",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Operator",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 37,
                            Code = "DFT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt taslak durumunda",
                            DisplayName = "Taslak",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 38,
                            Code = "DFT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record is in draft state",
                            DisplayName = "Draft",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 39,
                            Code = "AWT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt onay bekliyor",
                            DisplayName = "Onay Bekliyor",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 40,
                            Code = "AWT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record is waiting for approval",
                            DisplayName = "Awaiting Approval",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 41,
                            Code = "APR",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt onaylandı",
                            DisplayName = "Onaylandı",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 42,
                            Code = "APR",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record has been approved",
                            DisplayName = "Approved",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 43,
                            Code = "REJ",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt reddedildi",
                            DisplayName = "Reddedildi",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 44,
                            Code = "REJ",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record has been rejected",
                            DisplayName = "Rejected",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 45,
                            Code = "PSV",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt pasif / devre dışı",
                            DisplayName = "Pasif",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 46,
                            Code = "PSV",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record is passive / inactive",
                            DisplayName = "Passive",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 47,
                            Code = "DEL",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "tr-TR",
                            Description = "Kayıt silinmiş durumda",
                            DisplayName = "Silindi",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 48,
                            Code = "DEL",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Culture = "en-US",
                            Description = "Record has been deleted",
                            DisplayName = "Deleted",
                            EntityName = "Statu",
                            FieldName = "Code",
                            IsProtected = false,
                            ItemType = "Status",
                            LastStatusBy = 0,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<int>("ParameterDataTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDataTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("Group", "Key")
                        .IsUnique();

                    b.ToTable("Parameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "İkili doğrulama varsayılan kanal ve seçenekleri",
                            Group = "TwoFactor",
                            IsProtected = false,
                            Key = "Options",
                            LastStatusBy = 0,
                            ParameterDataTypeId = 15,
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3,
                            Template = "{\n  \"defaultChannel\": \"Sms\",\n  \"channels\": {\n    \"Sms\": { \"codeLength\": 6, \"expirySeconds\": 300 },\n    \"Email\": { \"codeLength\": 6, \"expirySeconds\": 300 },\n    \"Authenticator\": { \"digits\": 6, \"periodSeconds\": 30, \"hashAlgorithm\": \"SHA1\" }\n  }\n}",
                            Value = "{\n  \"defaultChannel\": \"Sms\"\n}"
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.ParameterDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("ParameterDataTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "NVarChar",
                            Code = 60,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "NVARCHAR logical length 50",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "NVarChar_50",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 2,
                            Category = "NVarChar",
                            Code = 70,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "NVARCHAR logical length 100",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "NVarChar_100",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            Category = "NVarChar",
                            Code = 80,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "NVARCHAR logical length 250",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "NVarChar_250",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "NVarChar",
                            Code = 90,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "NVARCHAR logical length 500",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "NVarChar_500",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "NVarChar",
                            Code = 100,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "NVARCHAR(MAX) logical length",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "NVarChar_Max",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Numeric",
                            Code = 200,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Unsigned 8-bit integer",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Byte",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Numeric",
                            Code = 210,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "16-bit integer",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "SmallInt",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 8,
                            Category = "Numeric",
                            Code = 220,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "32-bit integer",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Int",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 9,
                            Category = "Numeric",
                            Code = 230,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "64-bit integer",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "BigInt",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = "Numeric",
                            Code = 240,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Decimal(18,6)",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Decimal18_6",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Temporal",
                            Code = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "ISO date",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Date",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Temporal",
                            Code = 310,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "ISO time",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Time",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Temporal",
                            Code = 320,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "ISO datetime",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "DateTime",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 14,
                            Category = "Other",
                            Code = 900,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Boolean true/false",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Bool",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 15,
                            Category = "Other",
                            Code = 910,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Valid JSON",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Json",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 16,
                            Category = "Other",
                            Code = 920,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Encrypted secret",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Secret",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.Statu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastStatusAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("LastStatusBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("datetimeoffset(4)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DFT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record is in draft state",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Draft",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "AWT",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record is waiting for approval",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Awaiting Approval",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "APR",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record has been approved",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Approved",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "REJ",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record has been rejected",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Rejected",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "PSV",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record is passive / inactive",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Passive",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "DEL",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 0,
                            Description = "Record has been deleted",
                            IsProtected = false,
                            LastStatusBy = 0,
                            Name = "Deleted",
                            RowId = new Guid("00000000-0000-0000-0000-000000000000"),
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("ArchiX.Library.Entities.ConnectionAudit", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiX.Library.Entities.ConnectionServerWhitelist", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiX.Library.Entities.FilterItem", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiX.Library.Entities.LanguagePack", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiX.Library.Entities.Parameter", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.ParameterDataType", "DataType")
                        .WithMany()
                        .HasForeignKey("ParameterDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("ArchiX.Library.Entities.ParameterDataType", b =>
                {
                    b.HasOne("ArchiX.Library.Entities.Statu", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
