name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Restore
        run: dotnet restore ArchiX.sln

      - name: Build (warnings as errors)
        run: dotnet build ArchiX.sln -c Debug -warnaserror

      - name: Test
        run: dotnet test ArchiX.sln -c Debug -v minimal --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
