name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build_only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Restore
        run: dotnet restore ArchiX.sln

      - name: Build
        run: dotnet build ArchiX.sln -c Debug --no-restore -v minimal
